#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("Lawforall.Resource", IsApplication=true)]

namespace Lawforall
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f040001
			public const int branco = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int laranja = 2130968576;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int BK = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int book = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int ShapeExemplo = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int ShapeLaranja = 2130837507;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f060010
			public const int btnLogin = 2131099664;
			
			// aapt resource value: 0x7f06000e
			public const int btnSalvar = 2131099662;
			
			// aapt resource value: 0x7f06000d
			public const int edtEmail = 2131099661;
			
			// aapt resource value: 0x7f06000a
			public const int edtIdade = 2131099658;
			
			// aapt resource value: 0x7f060008
			public const int edtNome = 2131099656;
			
			// aapt resource value: 0x7f06000c
			public const int edtPassword = 2131099660;
			
			// aapt resource value: 0x7f060009
			public const int edtSobrenome = 2131099657;
			
			// aapt resource value: 0x7f06000b
			public const int edtUsername = 2131099659;
			
			// aapt resource value: 0x7f060003
			public const int imageView1 = 2131099651;
			
			// aapt resource value: 0x7f060002
			public const int linearLayout1 = 2131099650;
			
			// aapt resource value: 0x7f06000f
			public const int linearLayout2 = 2131099663;
			
			// aapt resource value: 0x7f060004
			public const int linearLayout3 = 2131099652;
			
			// aapt resource value: 0x7f060001
			public const int lstCategoria = 2131099649;
			
			// aapt resource value: 0x7f060007
			public const int textV = 2131099655;
			
			// aapt resource value: 0x7f060000
			public const int textView1 = 2131099648;
			
			// aapt resource value: 0x7f060011
			public const int txtCreate = 2131099665;
			
			// aapt resource value: 0x7f060006
			public const int txtDescricao = 2131099654;
			
			// aapt resource value: 0x7f060005
			public const int txtTitulo = 2131099653;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Categoria = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int CategoriaItem = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int Create = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int Login = 2130903043;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050000
			public const int app_name = 2131034112;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
